### ISSUE TITLE
Deals is deprecated and script throws an error (403).

### ISSUE THREAD

**Issue by videohead** [abedoret/hubspot-spreadsheet-datastudio#1]
The deals API is deprecated, and the code is throwing an error there.
I'm going to see if I can get it working with  CRM Pipelines API and walk that back through the pivots, etc. or just rewrite as queries.

Thanks for getting me started and past oAuth

**Comment by abedoret** [comment]
Hey Videohead.
I just committed the fix.
Thanks for letting me know.
